### ISSUE TITLE
Implicit import of modules

### ISSUE THREAD

**Issue by niutech** [AllAboutCode/EduBlocks#118] opened 2020-05-05 23:41 UTC
For beginners it is cumbersome to always remember to `import <module>` before using its functions. Why don't you implicitly import Python modules upon their first use? This is how MakeCode works - there are no explicit imports and all modules are available for instant use.

**Comment by JoshuaLowe1002** [comment] 2020-05-06 12:43
Hi @niutech, appreciate the feedback. Whilst I'm always open to new ideas for EduBlocks, here is why I am closing this issue:

EduBlocks is meant as a "stepping stone" program for people who are going from Blocks (Makecode or Scratch) to Text. Therefore, EduBlocks is meant to teach the Python Syntax so that when users eventually move onto Python they have learnt how to use it.

Therefore, I think it's a bad idea to implicitly import modules because that then puts the users using EduBlocks in bad habits and they will not learn that in Python you need to import libraries. 

MakeCode's implementation of Python isn't meant to be used as a stepping stone like EduBlocks but instead used as a way for users to code in Python. There are a number of ways MakeCode's python doesn't follow the "pythonical" way of doing things (forever loops are a function for example).

So it's by design that it might be annoying for beginners to remember to import libraries as it's good to instil good habits at this point rather than bad ones.

I hope this explains my position on this :)

**Closed by JoshuaLowe1002** 2020-05-06 12:43 UTC
