### ISSUE TITLE
When chrome is open, launching from Programming Menu fails

### ISSUE THREAD

**Issue by KramKroc** [AllAboutCode/EduBlocks#34] opened 2018-02-21 22:05 UTC
*Summary*

Attempted to launch EduBlocks from the Programming menu when Chromium is open but found it didn't  open successfully.

*Steps to Reproduce*
* Open Chromium
* Select EduBlocks from programming menu
* Terminal Open and indicates that EduBlocks is now listening on port 8081
* Browser based window opens

*Expected Behaviour*
* Brought to awesome application

*Actual Behaviour*
* Window displays error saying it could not connect to application or connection was reset

*System*
* OS: Raspian Stretch
* EduBlocks: 1.0.0

*Workaround*

Launch from terminal or kill chrome

**Comment by JoshuaLowe1002** [comment] 2018-02-22 20:32
Hello there,

Thanks for raising an issue!
Interesting issue, with the connection reset problem, that is normally fixed by simply rebooting the Pi. Does that work for you? Let me know how you get on, if it does not work, I would like to investigate this further!

Josh

**Comment by KramKroc** [comment] 2018-02-22 22:07
Have rebooted it a few times and retested it a number of times too and the behaviour is the same. If chromium browser is open I get ERR_CONNECTION_REFUSED when I attempt to launch via programming menu AND same for when I launch via the desktop icon/shortcut.

It always launches fine (regardless of whether chromium is open or not) when I use the cli/terminal command > edublocks

If I get a chance tomorrow I'll try on another pi to see if it's not just this one that has issues.

**Comment by JoshuaLowe1002** [comment] 2018-02-23 16:57
Ok. let me know how you get on!

**Comment by KramKroc** [comment] 2018-02-24 21:27
Hi @JoshuaLowe1002 I tried it on a separate Raspberry Pi 3 with the same end result unfortunately, i.e. cannot launch EduBlock from desktop or menu if chromium is open.

Have you not been able to reproduce this issue?

**Comment by JoshuaLowe1002** [comment] 2018-02-25 20:01
Hmm, let me see on my Pi and I will see if I can reproduce it!

**Comment by JoshuaLowe1002** [comment] 2018-03-11 14:06
Sorry for the delay on getting back, yes I can reproduce this and I am going to see where the problem lies

**Comment by KramKroc** [comment] 2018-06-06 07:15
Any updates on this folks? Would really like to recommend this to our CoderDojo group to try over the summer break and it would be great to do so without having to caveat any issues.

**Comment by JoshuaLowe1002** [comment] 2018-06-08 18:50
Hello! This bug is now fixed so if you run `curl -sSL get.edublocks.org | bash` and that will download the fixed version.

**Comment by KramKroc** [comment] 2018-06-15 06:39
Hi @JoshuaLowe1002 tested it out and it works! Great job. I noticed the version of the app was still 1.0 and I'm suggesting you start updating the version when you fix issues, just so people know if they are still on an old version or the newest sparkliest version with all the latest features and bug fixes.

**Comment by JoshuaLowe1002** [comment] 2018-06-15 21:16
Ah, I see. Looks like the automatic thing that changes that has broke. I'll look into it

**Comment by KramKroc** [comment] 2018-06-18 09:34
No need to reopen this @JoshuaLowe1002, I just wanted to flag it up for future releases :D I use this great utility with some of the projects I work with: https://github.com/peritus/bumpversion

**Closed** 2018-06-19 16:30 UTC
Labels: bug
